const rCR01FormFieldsDefaults = {
  dateForwardedToAcctg: {
    id: "dateForwardedToAcctg",
    value: "",
    name: "dateForwardedToAcctg",
    label: "Date Forwarded to Acctg",
    placeholder: "2018-07-22",
    type: "date",
    required: true,
  },
  project: {
    id: "project",
    value: "",
    name: "project",
    label: "Project",
    placeholder: "Project",
    type: "select",
    referenceNo_Error: "required",
    required: true,
    properties: [],
  },

  category: {
    id: "category",
    value: "",
    name: "category",
    label: "Category",
    placeholder: "Category",
    type: "select",
    referenceNo_Error: "required",
    properties: [],
    required: true,
  },

  particulars: {
    id: "particulars",
    value: "",
    name: "Particulars",
    label: "Particulars",
    placeholder: "Particulars",
    type: "standard",
    multiline: true,
    required: true,
  },

  supplier: {
    id: "supplier",
    value: "",
    name: "supplier",
    label: "Supplier",
    placeholder: "Supplier",
    type: "select",
    referenceNo_Error: "required",
    properties: [],
    required: true,
  },

  terms: {
    id: "terms",
    value: "",
    name: "terms",
    label: "Terms",
    placeholder: "Terms",
    type: "select",
    referenceNo_Error: "required",
    properties: [],
    required: true,
  },

  pO: {
    id: "pO",
    value: "",
    name: "pO",
    label: "PO Number",
    placeholder: "PO Number",
    type: "standard",
    required: true,
  },

  rFP: {
    id: "rFP",
    value: "",
    name: "rFP",
    label: "RFP Number",
    placeholder: "RFP Number",
    type: "standard",
    required: true,
  },
  amount: {
    id: "amount",
    value: "",
    name: "Amount",
    label: "Amount",
    placeholder: "Amount",
    type: "number",
    required: true,
  },

  pARemarks: {
    id: "pARemarks",
    value: "",
    name: "pARemarks",
    label: "PA Remarks",
    placeholder: "PA Remarks",
    type: "standard",
    multiline: true,
    required: true,
  },

  criticalOnWk: {
    id: "criticalOnWk",
    value: "",
    name: "critical On",
    label: "Critical On",
    placeholder: "Critical On",
    type: "standard",
    value: "",
    required: true,
  },
};
const rCR02FormFields = {
  rCR02Remarks: {
    id: "rCR02Remarks",
    value: "",
    name: "rCR02Remarks",
    label: "rCR02 Remarks",
    placeholder: "rCR02 Remarks",
    type: "string",
    multiline: true,
    required: true,
  },
};

const rCR03FormFields = {
  rCR03Remarks: {
    id: "rCR03Remarks",
    value: "",
    name: "rCR03Remarks",
    label: "rCR03 Remarks",
    placeholder: "rCR03 Remarks",
    type: "string",
    required: true,
    multiline: true,
  },
};

const rCR04FormFields = {
  rCR04WeekNo: {
    id: "rCR04WeekNo",
    value: "",
    name: "rCR04WeekNo",
    label: "Week No.",
    placeholder: "Week Number",
    type: "standard",
    required: true,
  },
  rCR04Status: {
    id: "rCR04Status",
    value: "",
    name: "rCR04Status",
    label: "Treasury Status",
    placeholder: "Treasury Status",
    type: "standard",
    required: true,
  },
  rCR04CheckNo: {
    id: "rCR04CheckNo",
    value: "",
    name: "rCR04CheckNo",
    label: "Check No.",
    placeholder: "Check No.",
    type: "standard",
    required: true,
  },
  rCR04PDCDate: {
    id: "rCR04PDCDate",
    value: "",
    name: "rCR04PDCDate",
    label: "PDC Date",
    placeholder: "PDC Date",
    type: "date",
    required: true,
  },
  rCR04OtherNameNotes: {
    id: "rCR04OtherNameNotes",
    value: "",
    name: "rCR04OtherNameNotes",
    label: "Other Name Notes",
    placeholder: "Other Name Notes",
    type: "standard",
    required: true,
  },
  rCR04DisbursementAcctg: {
    id: "rCR04DisbursementAcctg",
    value: "",
    name: "rCR04DisbursementAcctg",
    label: "Disbursement Account",
    placeholder: "Disbursement Account",
    type: "standard",
    required: true,
  },
  rCR04SINo: {
    id: "rCR04SINo",
    value: "",
    name: "rCR04SINo",
    label: "SI Number",
    placeholder: "SI Number",
    type: "standard",
    required: true,
  },
  rCR04SIDate: {
    id: "rCR04SIDate",
    value: "",
    name: "rCR04SIDate",
    label: "SI Date",
    placeholder: "SI Date",
    type: "date",
    required: true,
  },
  rCR04Comment: {
    id: "rCR04Comment",
    value: "",
    name: "rCR04Comment",
    label: "Comment",
    placeholder: "Comment",
    type: "standard",
    required: true,
  },
};

const _rCR01FormFields = {
  dateForwardedToAcctg: {
    id: "dateForwardedToAcctg",
    value: "",
    name: "dateForwardedToAcctg",
    label: "Date Forwarded to Acctg",
    placeholder: "2018-07-22",
    type: "date",
    required: true,
  },
  project: {
    id: "project",
    value: "",
    name: "project",
    label: "Project",
    placeholder: "Project",
    type: "select",
    referenceNo_Error: "required",
    required: true,
    properties: [],
  },

  category: {
    id: "category",
    value: "",
    name: "category",
    label: "Category",
    placeholder: "Category",
    type: "select",
    referenceNo_Error: "required",
    properties: [],
    required: true,
  },

  particulars: {
    id: "particulars",
    value: "",
    name: "Particulars",
    label: "Particulars",
    placeholder: "Particulars",
    type: "standard",
    multiline: true,
    required: true,
  },

  supplier: {
    id: "supplier",
    value: "",
    name: "supplier",
    label: "Supplier",
    placeholder: "Supplier",
    type: "select",
    referenceNo_Error: "required",
    properties: [],
    required: true,
  },

  terms: {
    id: "terms",
    value: "",
    name: "terms",
    label: "Terms",
    placeholder: "Terms",
    type: "select",
    referenceNo_Error: "required",
    properties: [],
    required: true,
  },

  pO: {
    id: "pO",
    value: "",
    name: "pO",
    label: "PO Number",
    placeholder: "PO Number",
    type: "standard",
    required: true,
  },

  rFP: {
    id: "rFP",
    value: "",
    name: "rFP",
    label: "RFP Number",
    placeholder: "RFP Number",
    type: "standard",
    required: true,
  },
  amount: {
    id: "amount",
    value: "",
    name: "Amount",
    label: "Amount",
    placeholder: "Amount",
    type: "number",
    required: true,
  },

  pARemarks: {
    id: "pARemarks",
    value: "",
    name: "pARemarks",
    label: "PA Remarks",
    placeholder: "PA Remarks",
    type: "standard",
    multiline: true,
    required: true,
  },

  criticalOnWk: {
    id: "criticalOnWk",
    value: "",
    name: "critical On",
    label: "Critical On",
    placeholder: "Critical On",
    type: "standard",
    value: "",
    required: true,
  },
};

const otherFormFields = {
  checkStatus: {
    id: "checkStatus",
    value: "",
    name: "checkStatus",
    label: "Check Status",
    placeholder: "Check Status",
    type: "standard",
    value: "",
    required: true,
  },
  rCR04Reference: {
    id: "rCR04Reference",
    value: "",
    name: "rCR04Reference",
    label: "RCR04 Reference",
    placeholder: "RCR04 Reference",
    type: "standard",
    value: "",
    required: true,
  },
  proposedCheckReleasedDate: {
    id: "proposedCheckReleasedDate",
    value: "",
    name: "proposedCheckReleasedDate",
    label: "Propose Check Released Date",
    placeholder: "Propose Check Released Date",
    type: "date",
    value: "",
    required: true,
  },
  numOfDays: {
    id: "numOfDays",
    value: "",
    name: "numOfDays",
    label: "Number of Days",
    placeholder: "Number of Days",
    type: "standard",
    value: "",
    required: true,
  },
  pdcDate: {
    id: "pdcDate",
    value: "",
    name: "pdcDate",
    label: "PDC Date",
    placeholder: "PDC Date",
    type: "date",
    value: "",
    required: true,
  },
  yearMonthWeek: {
    id: "yearMonthWeek",
    value: "",
    name: "yearMonthWeek",
    label: "Year Month Week",
    placeholder: "Year Month Week",
    type: "standard",
    value: "",
    required: true,
  },
  pdcDateWk: {
    id: "pdcDateWk",
    value: "",
    name: "pdcDateWk",
    label: "PDC Date Week",
    placeholder: "PDC Date Week",
    type: "date",
    value: "",
    required: true,
  },
};

const prepareDropdownProperties = (array, value, label) => {
  return array.map((item) => {
    return { value: item[value], label: item[label] };
  });
};

let headerToVariable = {
  // USE THIS TO FORCE THE VARIABLE SEQUENCE
  dateSubmitted: "Date Submitted",
  submittedBy: "Submitted By",
  referenceNo: "Reference No.",
  dateForwardedToAcctg: "Date Forwarded to Acctg",
  project: "Project",
  category: "Category",
  particulars: "Particular",
  supplier: "Supplier",
  terms: "Terms",
  pO: "PO #",
  rFP: "RFP #",
  amount: "Amount",
  pARemarks: "PA Remarks",
  criticalOnWk: "Critical On (Wk#)",
  requestStatus: "Request Status",
  rCR02Status: "RCR02 Status",
  rCR02Approver: "RCR02 Approver",
  rCR02DateApproved: "RCR02 Date Approved",
  rCR02Remarks: "RCR02 Remarks",
  rCR03Status: "RCR03 Status",
  rCR03Approver: "RCR03 Approver",
  rCR03DateApproved: "RCR03 Date Approved",
  rCR03Remarks: "RCR03 Remarks",
  checkStatus: "Check Status",
  rCR04Reference: "RCR04 Reference #",
  // proposedCheckReleasedDate: "PROPOSED CHECK RELEASED DATE",
  // numOfDays: "# of Days",
  // pdcDate: "PDC Date",
  // yearMonthWeek: "Year Month Week #",
  // week: "Week #",
  // pdcDateWk: "PDC Date / Wk#",

  rCR04WeekNo: "Week Number",
  rCR04Status: "Treasury Status",
  rCR04CheckNo: "Check Number",
  rCR04PDCDate: "PDC Date",
  rCR04OtherNameNotes: "Other Name Notes",
  rCR04DisbursementAcctg: "Disbursement Accounting",
  rCR04SINo: "SI Number",
  rCR04SIDate: "SI DATE",
  rCR04Comment: "Treasury Comment",
};
