const extraData = {
  RFTType: [
    {
      Description: "Allowances",
      "Is Active": true,
    },
    {
      Description: "Cash Advance",
      "Is Active": true,
    },
    {
      Description: "Cash Loan",
      "Is Active": true,
    },
    {
      Description: "Construction Materials",
      "Is Active": true,
    },
    {
      Description: "Freight Forwarder",
      "Is Active": true,
    },
    {
      Description: "Fuel and gas",
      "Is Active": true,
    },
    {
      Description: "Fund Transfer",
      "Is Active": true,
    },
    {
      Description: "Insurance",
      "Is Active": true,
    },
    {
      Description: "Medical Expenses",
      "Is Active": true,
    },
    {
      Description: "Miscellaneous",
      "Is Active": true,
    },
    {
      Description: "Office Equipment and Furniture",
      "Is Active": true,
    },
    {
      Description: "Office Supplies",
      "Is Active": true,
    },
    {
      Description: "Others",
      "Is Active": true,
    },
    {
      Description: "Overhead",
      "Is Active": true,
    },
    {
      Description: "Overhead-Rentals",
      "Is Active": true,
    },
    {
      Description: "Overhead-Water",
      "Is Active": true,
    },
    {
      Description: "Pasa Payroll",
      "Is Active": true,
    },
    {
      Description: "Petty Cash Fund",
      "Is Active": true,
    },
    {
      Description: "Professional Services",
      "Is Active": true,
    },
    {
      Description: "Reimbursement",
      "Is Active": true,
    },
    {
      Description: "Rental Expense",
      "Is Active": true,
    },
    {
      Description: "Repairs and maintenance",
      "Is Active": true,
    },
    {
      Description: "Representation",
      "Is Active": true,
    },
    {
      Description: "Safety Supplies",
      "Is Active": true,
    },
    {
      Description: "Subcontractor",
      "Is Active": true,
    },
    {
      Description: "Taxes and Licenses",
      "Is Active": true,
    },
    {
      Description: "Telephone and Communications",
      "Is Active": true,
    },
    {
      Description: "Testing Services",
      "Is Active": true,
    },
    {
      Description: "Tools & Equipment",
      "Is Active": true,
    },
    {
      Description: "Transportation",
      "Is Active": true,
    },
    {
      Description: "Utilities/Electricity",
      "Is Active": true,
    },
    {
      Description: "Utilities/Water Expenses",
      "Is Active": true,
    },
  ],
  vendorsMaster: [
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3191",
      "Vendor Name": "A&S CAD PLOTTING AND PRINTING SERVICES",
      "Address 1": "#22 PALMA GIL ST. OBRERO DAVAO CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "jamzgraphics@gmail.com",
      "Contact Number": "MR. JAMES A. SOLIVA",
      Terms: "0 Days",
      "Vendor Type": "Office Supplies",
      "": "",
    },

    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3085",
      "Vendor Name": "VILLAMOR, CHARITO",
      "Address 1":
        "SM Mall Novaliches Compound, Quirino Highway, Quezon City, Premiere St, Novaliches, Lungsod Quezon, Kalakhang Maynila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM2885",
      "Vendor Name": "VILLAMOR, JONIE",
      "Address 1": "Natividad Lopez St, Ermita, Manila, 1000 Metro Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM2233",
      "Vendor Name": "VILLAN, JESUSIMO",
      "Address 1":
        "Dr Arcadio Santos Ave, San Antonio, Para?aque, Metro Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM2140",
      "Vendor Name": "VILLANUEVA, IAN",
      "Address 1":
        "Dr Arcadio Santos Ave, San Antonio, Para?aque, Metro Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3061",
      "Vendor Name": "VILLANUEVA, JOMAR",
      "Address 1":
        "SM Mall Novaliches Compound, Quirino Highway, Quezon City, Premiere St, Novaliches, Lungsod Quezon, Kalakhang Maynila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM2548",
      "Vendor Name": "VILLANUEVA, JUNEMARK",
      "Address 1": "Agdao, Davao City, Davao del Sur",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM2042",
      "Vendor Name": "VILLANUEVA, MANUEL",
      "Address 1":
        "Dr Arcadio Santos Ave, San Antonio, Para?aque, Metro Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM2901",
      "Vendor Name": "VILLARALVO, GRINGO",
      "Address 1": "Natividad Lopez St, Ermita, Manila, 1000 Metro Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3045",
      "Vendor Name": "VILLARALVO, ROLANDO",
      "Address 1":
        "SM Mall Novaliches Compound, Quirino Highway, Quezon City, Premiere St, Novaliches, Lungsod Quezon, Kalakhang Maynila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3839",
      "Vendor Name": "VILLARTA, FERDINAND",
      "Address 1": "Natividad Lopez St, Ermita, Manila, 1000 Metro Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "N/A",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3960",
      "Vendor Name": "VILLEGAS, JOSEPH",
      "Address 1": "Natividad Lopez St, Ermita, Manila, 1000 Metro Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "N/A",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM1515",
      "Vendor Name": "VILLMAN COMPUTER SYSTEMS (WEST) INC.",
      "Address 1": "C 417 4/F BLDG B CYBERZONE SM MEGA MALL MANDALUYONG CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "ELVIE",
      Terms: "0 Days",
      "Vendor Type": "Computer Store",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001092",
      "Vendor Name": "VILLMAN COMPUTER SYSTEMS (WEST) INC._",
      "Address 1":
        "AX1 3/F ANNEX BLDG. SM CITY NORTH EDSA, NORTH AVE., STO. CRISTO, QUEZON CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Others",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM1996",
      "Vendor Name": "VIÃ‘AS, JOMAR",
      "Address 1":
        "Dr Arcadio Santos Ave, San Antonio, Para?aque, Metro Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001093",
      "Vendor Name": "VINCENT SANTY P. FOLIENTE",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Others",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM2818",
      "Vendor Name": "VIO, RONA",
      "Address 1": "Megaworld Blvd, Mandurriao, Iloilo City, 5000 Iloilo",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM2837",
      "Vendor Name": "VIOLATA, EMMAR",
      "Address 1": "Quirino Hwy, Novaliches, Quezon City, Metro Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001094",
      "Vendor Name": "VIRA PEST INC.",
      "Address 1": "B1 B15 PH-35 JOHN ST BRGY PARANAQUE CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": 8289259,
      Terms: "30 Days",
      "Vendor Type": "Testing Services",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001095",
      "Vendor Name": "VIRGEL ALDEA",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": 9160000000,
      Terms: "7 Days",
      "Vendor Type": "Sub Contractor",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3279",
      "Vendor Name": "VISAYAN EDUCATIONAL SUPPLY CORPORATION",
      "Address 1": "PLARIDEL COR. A.C. CORTES AVE CAMBARO MANDAUE CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Office Supplies",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VC1949",
      "Vendor Name": "VISAYAN ELECTRIC CO., INC.",
      "Address 1": "VECO ENGINEERING OFFICE J. PANIS STREET BANILAD, CEBU CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "VISAYAN ELECTRIC CO., INC.",
      Terms: "0 Days",
      "Vendor Type": "Utilities",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3265",
      "Vendor Name": "VISAYAS TRUCKERS EQUIPMENT AND QUARRY OPERATORS SE",
      "Address 1":
        "RM 211 NDI COMM'L COMPLEX A.S. FORTUNA ST. BAKILID MANDAUE CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "hermosillatessie@gmail.com",
      "Contact Number": "MS. TESSIE HERMOSILLA",
      Terms: "15 Days",
      "Vendor Type": "Others",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM2824",
      "Vendor Name": "VISAYAS, ANA LIZA",
      "Address 1": "Megaworld Blvd, Mandurriao, Iloilo City, 5000 Iloilo",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001096",
      "Vendor Name": "VISER - PHIL FORMWORK CORP",
      "Address 1": "9375 BALIBAD ROAD BALUBAT IST BRGY BALUBAD SILANG CAITE",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "sales@viserphilformworkcorp.com",
      "Contact Number": "MR. LARREN L. MAUHAY",
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001097",
      "Vendor Name": "VISIONPROPERTIES DEVELOPM...",
      "Address 1": "PASIG CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "VDC Group",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001098",
      "Vendor Name": "VM CONCEPCION CONSTRUCTION",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "7 Days",
      "Vendor Type": "Sub Contractor",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001099",
      "Vendor Name": "VM LIWANAG INDUSTRIES CORP.",
      "Address 1":
        "B5 L23, Ph1B San Lorenzo South Malitlit Sta. Rosa City,Laguna",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "(02)519-4860",
      Terms: "30 Days",
      "Vendor Type": "Others",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001100",
      "Vendor Name": "VONN ERNEST F. JAVIER",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Others",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM1751",
      "Vendor Name": "W.R.3 CONSTRUCTION SUPPLIES TRADING",
      "Address 1":
        "B-2 LOT 220 PHASE 1 L1 SUB-URBAN SAN JOSE MONTALBAN RODRIGUEZ RIZAL",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "Rowena Morales",
      Terms: "0 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001101",
      "Vendor Name": "W.V. NEW DAVAO GOLDSTAR HARDWARE",
      "Address 1": "Address",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": 9500000000,
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM4049",
      "Vendor Name": "WAAD, NIRBIN",
      "Address 1": "Natividad Lopez St, Ermita, Manila, 1000 Metro Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "N/A",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM2625",
      "Vendor Name": "WAHAB, DAVE",
      "Address 1": "Agdao, Davao City, Davao del Sur",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM4400",
      "Vendor Name": "WATER LOVERS PURIFIED DRINKING WATER",
      "Address 1":
        "DR. 9, ACASONS COMMERCIAL ARCADE II, BOLCAN ST., COR. JP CABAGUIO., AVE., DAVAO CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "RICK SEÃ‘EDO",
      Terms: "0 Days",
      "Vendor Type": "Others",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3385",
      "Vendor Name": "WDC TRADING",
      "Address 1": "13 JESUS ST. PLEASANT VIEW SUBD. TANDANG SORA QUEZON CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "catherine_dino@yahoo.com",
      "Contact Number": "KAT DINO",
      Terms: "0 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001102",
      "Vendor Name": "WEIDA PHILIPPINES INC.",
      "Address 1": "418 Tandang Sora Ext. Rgy 163. Sta Quiteria, Caloocan City",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "706-2002",
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001103",
      "Vendor Name": "WELD INDUSTRIAL SALES",
      "Address 1": "Manuali Porac Pampanga",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "weldjade@gmail.com",
      "Contact Number": "7549422/4753211",
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001104",
      "Vendor Name": "WELD POWERTOOLS INDUSTRIAL MACHINERY CORP.",
      "Address 1": "124 Domestic Road, Pasay City",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "0917-5240-671",
      Terms: "60 Days",
      "Vendor Type": "Tools and Equipment",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM1863",
      "Vendor Name": "WELD POWERTOOLS INDUSTRRIAL MACHINERY CORP.",
      "Address 1": "SB CABAHUG STREET IBABAO MANDAUE CITY,CEB",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "frederickdonasco18@gmail.com",
      "Contact Number": "Mr. Frederick Donasco",
      Terms: "0 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001105",
      "Vendor Name": "WELLMADE GROUP LTD",
      "Address 1":
        "15Th Floor, Times Plaza Bldg.Un Ave., Cor Taft Ave., Ermita Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "0086-2583557331",
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001106",
      "Vendor Name": "WELMAR MOTOR WORKS",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Others",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM4202",
      "Vendor Name": "WELTANCHAUNG CORPORATION",
      "Address 1": "#192 A. LUNA ST. BRGY. POBLACION, MANDALUYONG CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "weltanchaungcorp@weltanchaung.com",
      "Contact Number": "HAROLD C. MAGOS",
      Terms: "0 Days",
      "Vendor Type": "Sub Contractor",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001107",
      "Vendor Name": "WENJEM ENTERPRISES CORP.",
      "Address 1":
        "30 D Commonwealth Vill.Commonwealth Avenue,Matandang Balara Q.C.",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": 5874687,
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM1580",
      "Vendor Name": "WEST LAKE PERFORMANCE TIRES",
      "Address 1": "DAVAO CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "davaojunction@yahoo.com.ph",
      "Contact Number": "cherlyn",
      Terms: "0 Days",
      "Vendor Type": "Repair & Maintenance",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001108",
      "Vendor Name": "WHALE SHIPPING CORPORATION",
      "Address 1": "622 Evangelista St Zone 030 Brgy 308 Quiapo Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Travel Services",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM1962",
      "Vendor Name": "WHITE WHALE ENTERPRISES",
      "Address 1": "9-K APO STREET QUEZON CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "wwhaleenterprises@gmail.com",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Office Equipment and Furniture",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001109",
      "Vendor Name": "WHITEDWARF INC.",
      "Address 1":
        "U1-4 MAXSALONE CONDOMINIUM BARANGKA DRIVE PLAINVIEW, MANDALUYONG CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Others",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3122",
      "Vendor Name": "WHITELANDS EXPRESS, INC",
      "Address 1":
        "LOT9 BLK 12 11TH STREE GOLD MILS BUSINESS PARK MADUYA CARMONA, CAVITE",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "MR. CRIS C. IGNACIO",
      Terms: "30 Days",
      "Vendor Type": "Freight Forwarder",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM1857",
      "Vendor Name": "WHL HOUSEHOLD FIXTURES TRADING",
      "Address 1": "1109 Soler St., Binondo Manila City",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "maetianyin7@gmail.com",
      "Contact Number": "Ms. Angelica T. Jaro",
      Terms: "0 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001110",
      "Vendor Name": "WIL-AN ALUMINUM CENTER INC.",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001111",
      "Vendor Name": "WILCON DEPOT INC.",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "634-70-80/634-83-88",
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM1914",
      "Vendor Name": "WILCON DEPOT INC.- BALINTAWAK",
      "Address 1": "1274 EDSA BRGY. APOLONIO SAMSON QUEZON CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "balintawak@wilcon.com.ph",
      "Contact Number": "MS. ERRALYN EDUARTE",
      Terms: "0 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3210",
      "Vendor Name": "WILCON DEPOT INC.-VALENZUELA",
      "Address 1": "202 MC ARTHUR HI-WAY, BRGY. DALANDANAN VALUNEZUELA",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "MS. LIZA BOLANOS/NICOLE DOMINGO",
      Terms: "0 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3135",
      "Vendor Name": "WILCON DEPOT, INC - DAVAO",
      "Address 1": "MC ARTHUR BRGY MATINA APLAYA, DAVAO DEL SUR",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "MR. GERICK L. DEPOSA",
      Terms: "0 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3240",
      "Vendor Name": "WILCON DEPOT, INC.- MATANDANG BALARA",
      "Address 1": "LOT 946-C FERIA RD. MATANDANG BALARA 1119 QUEZON CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "MS. NILBE MENDIORO",
      Terms: "0 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3371",
      "Vendor Name": "WILCON DEPOT, INC.- PASONG TAMO",
      "Address 1": "PASONG TAMO EXTENSION BRGY. BANGKAL MAKATI CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "MR. ALWIN JOHN CORDOVA",
      Terms: "0 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM1518",
      "Vendor Name": "WILFREDO ARANZADO",
      "Address 1": 4,
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "WILFREDO ARANZADO",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "",
      "Vendor Code": "VC1613",
      "Vendor Name": "WILFREDO BENITO",
      "Address 1": "PASIG CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "WILFREDO BENITO",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM1594",
      "Vendor Name": "WILLMOORE BUILDERS AND DEVELOPMENT INC.",
      "Address 1":
        "NATIONAL HIGHWAY PUROK ISLAM, BRGY LUN PADIDU, MALAPATAN SARANGANI PROVINCE",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "willmoorebuilders@gmail.com",
      "Contact Number": "WILMER P. MORALES",
      Terms: "0 Days",
      "Vendor Type": "Sub Contractor",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001112",
      "Vendor Name": "WILSON ANTIPUESTO",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "7 Days",
      "Vendor Type": "Sub Contractor",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001113",
      "Vendor Name": "WILSON COGOLLODO",
      "Address 1": "225 Edc Bldg Reina Regente St Binondo Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": 9750000000,
      Terms: "7 Days",
      "Vendor Type": "Sub Contractor",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001227",
      "Vendor Name": "WILSON SAMBALOD",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001114",
      "Vendor Name": "WINDOWAY TRADING INC.",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Others",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001115",
      "Vendor Name": "WINMIL INDUSTRIAL SALES CORP.",
      "Address 1": "#52 G. Roxas St., Brgy. Manresa, Quezon City",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "winmilindustrialsales@gmail.com",
      "Contact Number": "935-9449 / 475-2417 / 441-0136",
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3451",
      "Vendor Name": "WINNIE R. PORMANES",
      "Address 1": "ZONE 5 SAN ANTONIO BOMBON CAMARINES SUR",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "WINNIE R. PORMANES",
      Terms: "0 Days",
      "Vendor Type": "Sub Contractor",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001116",
      "Vendor Name": "WINNING SET TRADING",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": 361.7705,
      Terms: "30 Days",
      "Vendor Type": "Parts Supplier",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM1683",
      "Vendor Name": "WIZARD MANPOWER & ALLIED SERVICES INC.",
      "Address 1": "Suite 409 Bldg. #815 Quezon Avenue, Quezon City",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "atty. Giovanni Melgar",
      Terms: "0 Days",
      "Vendor Type": "Manpower Agency",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001117",
      "Vendor Name": "WIZARD MANPOWER & ALLIED SERVICES INC._",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Manpower Agency",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Head Office",
      "Contract Package": "Contract ALL",
      Tower: "Tower ALL",
      Zone: "Zone ALL",
      "Vendor Code": "VM1697",
      "Vendor Name": "WOLFBYTE COMPUTER SERVICES",
      "Address 1":
        "RM 1 MEZZANINE FLR R. FLORETE BLDG COR RIZAL MARIA CLARA ILOILO CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "WOLFBYTE COMPUTER SERVICES",
      Terms: "0 Days",
      "Vendor Type": "Computer Store",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001118",
      "Vendor Name": "WOODBISON CONSTRUCTION & SUPPLY",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "7 Days",
      "Vendor Type": "Sub Contractor",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM1713",
      "Vendor Name": "World Class Laminate Inc",
      "Address 1": "CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "brice",
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001119",
      "Vendor Name": "WORLD HOME DEPOT CORPORATION",
      "Address 1":
        "#20 FORTUNE AVENUE CORNER SANTAN STREET BARANGAY FORTUNE MARIKINA CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "arianne.daclag@worldhomedepot.com",
      "Contact Number": "MS. MERCY ANN F. CAPITULO",
      Terms: "45 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001120",
      "Vendor Name": "WORLD URBAN INTEGRATED SUPPLIES & BUILDERS INC.",
      "Address 1": "262 Del Monte Ave.,Cor Mayon Stquezon City",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM1848",
      "Vendor Name": "WORLDWIDE BUILDING SOLUTIONS,INC.",
      "Address 1": "SACRIS ROAD EXTENSION BRGY. TIPOLO MANDAUE CITY,CEBU",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "honeylen.rosal@wwsteelgroup.com",
      "Contact Number": "Ms. Honeylen Rosal",
      Terms: "0 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001121",
      "Vendor Name": "WRUKSIN ELECTRICAL PRODUCTS TRADING",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM4200",
      "Vendor Name": "WS-R ENGINEERING SERVICES",
      "Address 1": "58 SAPANG BAKAW LAWANG BATO 1447 CITY OF VALENZUELA",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "leorollan82@gmail.com",
      "Contact Number": "ENGR. LEO V. ROLLAN",
      Terms: "0 Days",
      "Vendor Type": "Sub Contractor",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001122",
      "Vendor Name": "WTA ARCHITECTURE + DESIGN STUDIO",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Others",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3200",
      "Vendor Name": "WV NEW DAVAO GOLDSTAR HARDAWARE CO., INC.",
      "Address 1":
        "34 LAPU-LAPU STREET. AGDAO, DAVAO CITY DAVAO DEL SUR PHILIPPINES 8000",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "MS. HAZEL MARTINEZ",
      Terms: "0 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001123",
      "Vendor Name": "X10 TRADING",
      "Address 1":
        "409 3Rd Ave., Cor M. H. Delpilar St., 119Caloocanphilippines",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": 5479059,
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3483",
      "Vendor Name": "XACT ENTERPRISE",
      "Address 1":
        "25 CATHERINE ST. PARKWAY VILLAGE BRGY. APOLONIO SAMSON, QUEZON CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "psalmong720@gmail.com",
      "Contact Number": "PSALM EBENEZER TAN ONG",
      Terms: "30 Days",
      "Vendor Type": "Repair & Maintenance",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM4269",
      "Vendor Name": "XANDER MANGABO",
      "Address 1": "Pasig City",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "XANDER MANGABO",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001124",
      "Vendor Name": "XANJO TIRE SUPPLY",
      "Address 1": "732 Calero St Quiapo Manila",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Parts Supplier",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001125",
      "Vendor Name": "XIRRUS INC.",
      "Address 1": "6F JEFER PLACE BLDG 19 EISENHOWER ST. GREENHILSS SAN JUAN",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "30 Days",
      "Vendor Type": "Software Services",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "Megaworld Iloilo Business Park, Iloilo City",
      "Contract Package": "Contract ALL",
      Tower: "Tower ALL",
      Zone: "Zone ALL",
      "Vendor Code": "VM1603",
      "Vendor Name": "XT-XIAMEN KDSBUILDING MATERIAL CO., LTD.",
      "Address 1":
        "302 NO.14 QIAOFULI.QIANPU WEST ROAD. SIMING DISTRICT. XIAMEN CHINA",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "7 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Head Office",
      "Contract Package": "VDC Head Office Admin",
      Tower: "",
      Zone: "",
      "Vendor Code": "V001441",
      "Vendor Name": "XYLEXFERENE L. DELA TORRE",
      "Address 1": "MANDALUYONG CITY",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "7 Days",
      "Vendor Type": "Professional Services",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM2771",
      "Vendor Name": "YABUT, ELMER JOHN",
      "Address 1": "Megaworld Blvd, Mandurriao, Iloilo City, 5000 Iloilo",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM3785",
      "Vendor Name": "YAC, JONNEL",
      "Address 1": "P. Basubas St, Tipolo, Mandaue City, 6014 Cebu",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "N/A",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "VM4161",
      "Vendor Name": "YAC, STEWART",
      "Address 1": "P. Basubas St, Tipolo, Mandaue City, 6014 Cebu",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "N/A",
      Terms: "0 Days",
      "Vendor Type": "Employee",
      "": "",
    },
    {
      "Group of Companies": "Vision Properties Development Corporation",
      Site: "VDC Central Warehouse, Novaliches",
      "Contract Package": "VDC Central Warehouse, Novaliches",
      Tower: "GEN REQ",
      Zone: "GEN REQ",
      "Vendor Code": "V001126",
      "Vendor Name": "YALE HARDWARE CORP.,",
      "Address 1": "",
      "Address 2": "",
      "Address 3": "",
      "Email Address": "",
      "Contact Number": "733-19-88 / 733-2653",
      Terms: "30 Days",
      "Vendor Type": "Construction Materials",
      "": "",
    },
  ],
  disbursementAccounts: [
    {
      "Disbursement Code": 4201101,
      "Disbursement Account": "Safety",
      "": "",
    },
    {
      "Disbursement Code": 4201102,
      "Disbursement Account": "Tools",
      "": "",
    },
    {
      "Disbursement Code": 4201103,
      "Disbursement Account": "Construction Materials",
      "": "",
    },
    {
      "Disbursement Code": 4201108,
      "Disbursement Account": "MEPFS",
      "": "",
    },
    {
      "Disbursement Code": 4201300,
      "Disbursement Account": "Labor - Admin - Billable Works",
      "": "",
    },
    {
      "Disbursement Code": 4201301,
      "Disbursement Account": "Labor - Admin - Rectification Works",
      "": "",
    },
    {
      "Disbursement Code": 4201302,
      "Disbursement Account": "Labor - Admin - Support Group",
      "": "",
    },
    {
      "Disbursement Code": 4201400,
      "Disbursement Account": "Labor - PasaPayroll - Billable Works",
      "": "",
    },
    {
      "Disbursement Code": 4201401,
      "Disbursement Account": "Labor - PasaPayroll - Rectification Works",
      "": "",
    },
    {
      "Disbursement Code": 4201402,
      "Disbursement Account": "Labor - PasaPayroll - Support Group",
      "": "",
    },
    {
      "Disbursement Code": 4201500,
      "Disbursement Account": "Labor - Subcontractual - Billable Works",
      "": "",
    },
    {
      "Disbursement Code": 4201501,
      "Disbursement Account": "Labor - Subcontractual - Rectification Works",
      "": "",
    },
    {
      "Disbursement Code": 4201502,
      "Disbursement Account": "Labor - Subcontractual - Support Group",
      "": "",
    },
    {
      "Disbursement Code": 4201601,
      "Disbursement Account": "Overhead-Light/Electricity",
      "": "",
    },
    {
      "Disbursement Code": 4201602,
      "Disbursement Account": "Overhead-Telephone and Communications",
      "": "",
    },
    {
      "Disbursement Code": 4201603,
      "Disbursement Account": "Overhead-Water",
      "": "",
    },
    {
      "Disbursement Code": 4201604,
      "Disbursement Account": "Overhead-Office Supplies",
      "": "",
    },
    {
      "Disbursement Code": 4201605,
      "Disbursement Account": "Overhead-Rentals",
      "": "",
    },
    {
      "Disbursement Code": 4201606,
      "Disbursement Account": "Overhead-Depreciation",
      "": "",
    },
    {
      "Disbursement Code": 4201607,
      "Disbursement Account": "Overhead- Repairs and Maintenance",
      "": "",
    },
    {
      "Disbursement Code": 4201608,
      "Disbursement Account": "Overhead-Insurance",
      "": "",
    },
    {
      "Disbursement Code": 4201609,
      "Disbursement Account": "Overhead-Logistics ",
      "": "",
    },
    {
      "Disbursement Code": 4201610,
      "Disbursement Account": "Overhead-Meals&Representation",
      "": "",
    },
    {
      "Disbursement Code": 4201611,
      "Disbursement Account": "Overhead-Security Wages",
      "": "",
    },
    {
      "Disbursement Code": 4201612,
      "Disbursement Account": "Overhead-Fuel & Gas",
      "": "",
    },
    {
      "Disbursement Code": 4201613,
      "Disbursement Account": "Overhead-Others",
      "": "",
    },
    {
      "Disbursement Code": 5101001,
      "Disbursement Account":
        "Admin - Advertising Expense - Public Relations & Media",
      "": "",
    },
    {
      "Disbursement Code": 5102101,
      "Disbursement Account": "Admin - Salaries & Wages",
      "": "",
    },
    {
      "Disbursement Code": 5102112,
      "Disbursement Account": "Admin - Employee Training and Seminars Expense",
      "": "",
    },
    {
      "Disbursement Code": 5102113,
      "Disbursement Account": "Admin - Recruitment and Hiring Expense",
      "": "",
    },
    {
      "Disbursement Code": 5102114,
      "Disbursement Account": "Admin - Outside Services - Manpower Agency",
      "": "",
    },
    {
      "Disbursement Code": 5102115,
      "Disbursement Account": "Admin - Management and Consultancy Expense",
      "": "",
    },
    {
      "Disbursement Code": 5102116,
      "Disbursement Account": "Admin - Legal and Professional Fees Expense",
      "": "",
    },
    {
      "Disbursement Code": 5102117,
      "Disbursement Account": "Admin - Meeting Expenses",
      "": "",
    },
    {
      "Disbursement Code": 5102118,
      "Disbursement Account":
        "Admin - Travel Expenses - transportation, accommodation, meals, per diem",
      "": "",
    },
    {
      "Disbursement Code": 5102201,
      "Disbursement Account":
        "Admin - Insurance Expense - Bldg & Facilities, and Fleet",
      "": "",
    },
    {
      "Disbursement Code": 5102301,
      "Disbursement Account": "Admin - Repairs & Maintenance - Equipment",
      "": "",
    },
    {
      "Disbursement Code": 5102304,
      "Disbursement Account":
        "Admin - Repairs & Maintenance - Bldg & Facilities",
      "": "",
    },
    {
      "Disbursement Code": 5102305,
      "Disbursement Account": "Admin - Repairs & Maintenance - Vehicles",
      "": "",
    },
    {
      "Disbursement Code": 5102401,
      "Disbursement Account": "Admin - Rental Expense",
      "": "",
    },
    {
      "Disbursement Code": 5102402,
      "Disbursement Account": "Admin - Light/Electricity Expense",
      "": "",
    },
    {
      "Disbursement Code": 5102404,
      "Disbursement Account": "Admin - Water Expense",
      "": "",
    },
    {
      "Disbursement Code": 5102405,
      "Disbursement Account": "Admin - Office Supplies",
      "": "",
    },
    {
      "Disbursement Code": 5102406,
      "Disbursement Account": "Admin - Non-Capitalizeable IT Equipment",
      "": "",
    },
    {
      "Disbursement Code": 5102407,
      "Disbursement Account": "Admin - Outside Software Fees",
      "": "",
    },
    {
      "Disbursement Code": 5102702,
      "Disbursement Account": "Admin - Representation & Entertainment Expense",
      "": "",
    },
    {
      "Disbursement Code": 5102703,
      "Disbursement Account": "Admin - Miscellaneous Expense",
      "": "",
    },
    {
      "Disbursement Code": 5102704,
      "Disbursement Account": "Admin - Bank Charges Expense",
      "": "",
    },
    {
      "Disbursement Code": 5102705,
      "Disbursement Account": "Admin - Taxes & Licenses Expense",
      "": "",
    },
    {
      "Disbursement Code": 5102707,
      "Disbursement Account": "Admin - Penalty and Charges",
      "": "",
    },
    {
      "Disbursement Code": 7100002,
      "Disbursement Account": "Admin - Interests Expense",
      "": "",
    },
    {
      "Disbursement Code": 9000001,
      "Disbursement Account": "VCentral - Overhead - Mall Operation",
      "": "",
    },
    {
      "Disbursement Code": 1101101,
      "Disbursement Account":
        "Cash in Bank - Bank of Makati Head Office (﻿1510-2001-725)",
      "": "",
    },
    {
      "Disbursement Code": 1101102,
      "Disbursement Account": "Cash in Bank - BDO East Maya (﻿0016-3007-6382)",
      "": "",
    },
    {
      "Disbursement Code": 1101103,
      "Disbursement Account":
        "Cash in Bank - BPI QC-Sto Domingo (﻿000213-4072-01)",
      "": "",
    },
    {
      "Disbursement Code": 1101104,
      "Disbursement Account":
        "Cash in Bank - China Bank Savings G Araneta (﻿6117-0000-0264)",
      "": "",
    },
    {
      "Disbursement Code": 1101105,
      "Disbursement Account":
        "Cash in Bank - DBP Quezon Ave (﻿0460-0360-10030)",
      "": "",
    },
    {
      "Disbursement Code": 1101106,
      "Disbursement Account": "Cash in Bank - EWB Molino (2000-02162-384)",
      "": "",
    },
    {
      "Disbursement Code": 1101107,
      "Disbursement Account": "Cash in Bank - EWB Molino (﻿2000-17891-177)",
      "": "",
    },
    {
      "Disbursement Code": 1101108,
      "Disbursement Account":
        "Cash in Bank - PNB QC-Tomas Morato (﻿1207-7000-0865)",
      "": "",
    },
    {
      "Disbursement Code": 1101109,
      "Disbursement Account": "Cash in Bank - RCBC Bacoor (﻿0000-0534500-0064)",
      "": "",
    },
    {
      "Disbursement Code": 1101110,
      "Disbursement Account":
        "Cash in Bank - RCBC SA Bacoor ﻿(0000-0902124-3111)",
      "": "",
    },
    {
      "Disbursement Code": 1101111,
      "Disbursement Account":
        "Cash in Bank - Robinsons Bank Del Monte (﻿1002-3010-0000-461)",
      "": 12,
    },
    {
      "Disbursement Code": 1101112,
      "Disbursement Account": "Cash in Bank - SB Alimall (﻿0160-06561-1001)",
      "": "",
    },
    {
      "Disbursement Code": 1102007,
      "Disbursement Account": "Advances to Subcon",
      "": "",
    },
    {
      "Disbursement Code": 1102008,
      "Disbursement Account": "Advances to Supplier - Asset",
      "": "",
    },
    {
      "Disbursement Code": 1102009,
      "Disbursement Account": "Advances to Supplier - Non-Asset",
      "": "",
    },
    {
      "Disbursement Code": 1202004,
      "Disbursement Account": "Fixed Assets - Furniture & Fixtures",
      "": "",
    },
    {
      "Disbursement Code": 1202005,
      "Disbursement Account": "Fixed Assets - Heavy Tools",
      "": "",
    },
    {
      "Disbursement Code": 1202006,
      "Disbursement Account": "Fixed Assets - Computer Equipments",
      "": "",
    },
    {
      "Disbursement Code": 1202007,
      "Disbursement Account": "Fixed Assets - Vehicles",
      "": "",
    },
    {
      "Disbursement Code": 1202008,
      "Disbursement Account": "Fixed Assets - Heavy Equipments",
      "": "",
    },
    {
      "Disbursement Code": 1202009,
      "Disbursement Account": "Fixed Assets - Lease Hold Improvements",
      "": "",
    },
    {
      "Disbursement Code": 1202010,
      "Disbursement Account": "Fixed Assets - Computer Software & Licenses",
      "": "",
    },
    {
      "Disbursement Code": 1202011,
      "Disbursement Account": "Fixed Assets - Formworks",
      "": "",
    },
    {
      "Disbursement Code": 1101001,
      "Disbursement Account": "Petty Cash Fund",
      "": "",
    },
    {
      "Disbursement Code": 2201003,
      "Disbursement Account": "Installment Payable",
      "": "",
    },
    {
      "Disbursement Code": 2201004,
      "Disbursement Account": "Finance Lease Liability- Long Term",
      "": "",
    },
    {
      "Disbursement Code": 2201005,
      "Disbursement Account": "Loans Payable - Long-Term",
      "": "",
    },
    {
      "Disbursement Code": 2201100,
      "Disbursement Account": "Advances from Stockholder",
      "": "",
    },
    {
      "Disbursement Code": "",
      "Disbursement Account": "OFFICE EQUIPMENT ",
      "": "",
    },
    {
      "Disbursement Code": "",
      "Disbursement Account": "GOVERMENT ",
      "": "",
    },
  ],
  isLoading: false,
};
